-- =============================================================================
-- ระบบสรุปคอมเมนต์แจ้งปัญหา — สำนักงานเขตทวีวัฒนา
-- วิธีใช้: Supabase → SQL Editor → วางไฟล์นี้ทั้งไฟล์ → Run (รันซ้ำได้ ไม่ลบข้อมูล)
--
-- ความปลอดภัย: หน้าเว็บเปิดได้ทุกคน แต่ข้อมูลทุกตารางเปิด Row Level Security
--   - ไม่ได้ล็อกอิน (anon)         : ไม่เห็นอะไรเลย
--   - สมัครแล้วแต่ยังไม่อนุมัติ (pending): ไม่เห็นอะไรเลย
--   - ผู้ดู (viewer)               : อ่านได้อย่างเดียว
--   - ผู้ดูแล (admin)              : อ่าน/เขียน/นำเข้า/จัดการผู้ใช้
--   คนแรกที่สมัครจะเป็นผู้ดูแลอัตโนมัติ
-- =============================================================================

-- ---------------------------------------------------------------------------
-- ตาราง
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'pending' check (role in ('admin', 'viewer', 'pending')),
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id text primary key,
  fb_id text unique,                 -- เลขโพสต์ที่อ่านได้จาก Comment ID
  fb_key text,                       -- รหัสจากลิงก์ที่ลงทะเบียน (pfbid / เลขโพสต์) ใช้จับคู่กับ CSV
  fb_url text check (fb_url is null or fb_url ~* '^https://([a-z0-9-]+\.)?(facebook\.com|fb\.com|fb\.watch|fb\.me)/'),
  url text,                          -- ลิงก์โพสต์ที่อ่านได้จาก CSV
  title text not null default 'โพสต์ใหม่',
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid,
  first_imported timestamptz,
  last_imported timestamptz
);
create unique index if not exists posts_fb_key_uniq on public.posts(fb_key) where fb_key is not null and fb_key <> '';

create table if not exists public.comments (
  id text primary key,
  post_id text not null references public.posts(id) on update cascade,
  parent_id text,
  text text,
  ts timestamp,                      -- เวลาคอมเมนต์ (เวลาไทย)
  like_count int default 0,
  reply_count int default 0,
  url text,
  user_id text,
  user_name text,
  user_homepage text,
  imported_at timestamptz default now(),
  auto_label text,
  auto_category text,
  auto_urgency text,
  auto_location text,
  matched text,
  is_problem boolean not null default false,
  category text,
  urgency text,
  location text,
  review text not null default 'pending' check (review in ('pending', 'confirmed', 'rejected')),
  status text,
  note text,
  updated_at timestamptz,
  updated_by uuid
);
create index if not exists comments_post_idx on public.comments(post_id);
create index if not exists comments_ts_idx on public.comments(ts);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  comment_id text,
  at timestamptz not null default now(),
  user_id uuid,
  user_email text,
  field text,
  old_value text,
  new_value text
);
create index if not exists history_comment_idx on public.history(comment_id);

create table if not exists public.imports (
  id text primary key,
  at timestamptz not null default now(),
  filename text,
  post_id text,
  total int default 0,
  added int default 0,
  duplicate int default 0,
  user_id uuid,
  user_email text
);

create table if not exists public.keywords (
  grp text primary key,
  words text
);

-- ---------------------------------------------------------------------------
-- สิทธิ์ผู้ใช้
-- ---------------------------------------------------------------------------
create or replace function public.app_role() returns text
language sql stable security definer set search_path = public as $$
  select coalesce((select role from public.profiles where user_id = auth.uid()), 'anon')
$$;
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public as $$ select public.app_role() = 'admin' $$;
create or replace function public.is_member() returns boolean
language sql stable security definer set search_path = public as $$ select public.app_role() in ('admin', 'viewer') $$;

-- สมัครใหม่ → สร้าง profile (คนแรกเป็นผู้ดูแล คนต่อไปรออนุมัติ)
create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(user_id, email, display_name, role)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)),
          case when exists (select 1 from public.profiles where role = 'admin') then 'pending' else 'admin' end)
  on conflict (user_id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.set_user_role(p_user uuid, p_role text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'เฉพาะผู้ดูแล'; end if;
  if p_role not in ('admin', 'viewer', 'pending') then raise exception 'สิทธิ์ไม่ถูกต้อง'; end if;
  if p_role <> 'admin' and (select role from profiles where user_id = p_user) = 'admin'
     and (select count(*) from profiles where role = 'admin') <= 1 then
    raise exception 'ต้องมีผู้ดูแลอย่างน้อย 1 คน';
  end if;
  update profiles set role = p_role where user_id = p_user;
end $$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.posts    enable row level security;
alter table public.comments enable row level security;
alter table public.history  enable row level security;
alter table public.imports  enable row level security;
alter table public.keywords enable row level security;

revoke all on public.profiles, public.posts, public.comments, public.history, public.imports, public.keywords from anon;
grant select on public.profiles, public.posts, public.comments, public.history, public.imports, public.keywords to authenticated;
grant insert, update, delete on public.posts, public.comments, public.keywords to authenticated;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

do $$
declare t text;
begin
  foreach t in array array['posts', 'comments', 'history', 'imports', 'keywords'] loop
    execute format('drop policy if exists %1$s_read on public.%1$s', t);
    execute format('create policy %1$s_read on public.%1$s for select to authenticated using (public.is_member())', t);
  end loop;
  foreach t in array array['posts', 'comments', 'keywords'] loop
    execute format('drop policy if exists %1$s_write on public.%1$s', t);
    execute format('create policy %1$s_write on public.%1$s for all to authenticated using (public.is_admin()) with check (public.is_admin())', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- ประวัติการแก้ไข (บันทึกอัตโนมัติ ว่าใครแก้อะไร)
-- ---------------------------------------------------------------------------
create or replace function public.log_comment_change() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  f text;
  o text;
  n text;
  who_email text;
begin
  if current_setting('app.skip_history', true) = '1' then return new; end if;
  select email into who_email from profiles where user_id = auth.uid();
  foreach f in array array['is_problem', 'category', 'urgency', 'location', 'review', 'status', 'note'] loop
    execute format('select ($1).%1$I::text, ($2).%1$I::text', f) into o, n using old, new;
    if o is distinct from n then
      insert into history(comment_id, user_id, user_email, field, old_value, new_value)
      values (new.id, auth.uid(), who_email, f, o, n);
    end if;
  end loop;
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end $$;
drop trigger if exists comments_history on public.comments;
create trigger comments_history before update on public.comments
  for each row execute function public.log_comment_change();

-- ---------------------------------------------------------------------------
-- นำเข้าคอมเมนต์ (หน้าเว็บอ่าน CSV + คัดกรองแล้ว ส่งมาเป็นชุด)
--   ตัดซ้ำด้วย Comment ID · จับคู่โพสต์: เลขโพสต์ → โพสต์ที่เลือก → ลิงก์ที่ลงทะเบียน → สร้างใหม่
-- ---------------------------------------------------------------------------
create or replace function public.import_comments(p_rows jsonb, p_filename text, p_post text, p_batch text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  g record;
  pid text;
  tp record;
  warns text[] := '{}';
  post_ids text[] := '{}';
  n_total int := 0;
  n_added int := 0;
  n_dup int := 0;
  n int;
  who_email text;
begin
  if not public.is_admin() then raise exception 'เฉพาะผู้ดูแล'; end if;
  select email into who_email from profiles where user_id = auth.uid();
  perform set_config('app.skip_history', '1', true);

  for g in
    select r->>'fb_id' as fb_id,
           coalesce(max(nullif(r->>'post_url', '')), '') as post_url,
           coalesce(max(nullif(r->>'post_key', '')), '') as post_key,
           jsonb_agg(r) as rows
    from jsonb_array_elements(p_rows) r
    where coalesce(r->>'id', '') <> ''
    group by r->>'fb_id'
  loop
    pid := null;
    select id into pid from posts where fb_id = g.fb_id;
    if pid is not null then
      if p_post is not null and p_post <> pid then
        warns := warns || 'ไฟล์นี้เป็นของโพสต์อื่นในระบบ — นำเข้าไปที่โพสต์ที่ถูกต้องให้แล้ว'::text;
      end if;
    end if;
    if pid is null and p_post is not null then
      select id, fb_id, fb_key into tp from posts where id = p_post;
      if found and tp.fb_id is null and (coalesce(tp.fb_key, '') = '' or tp.fb_key in (g.post_key, g.fb_id)) then
        update posts set fb_id = g.fb_id, url = g.post_url where id = p_post;
        pid := p_post;
      end if;
    end if;
    if pid is null then
      select id into pid from posts
       where fb_id is null and fb_key <> '' and fb_key in (nullif(g.post_key, ''), g.fb_id) limit 1;
      if pid is not null then
        update posts set fb_id = g.fb_id, url = g.post_url where id = pid;
      end if;
    end if;
    if pid is null then
      pid := g.fb_id;
      insert into posts(id, fb_id, fb_key, url, title, created_by)
      values (pid, g.fb_id, nullif(g.post_key, ''), g.post_url, 'โพสต์ ' || right(g.fb_id, 6), auth.uid())
      on conflict (id) do nothing;
      if p_post is not null then
        warns := warns || 'ไฟล์ไม่ตรงกับลิงก์ของโพสต์ที่เลือก — สร้างเป็นโพสต์ใหม่ให้แล้ว ตรวจชื่อโพสต์อีกครั้ง'::text;
      end if;
    end if;
    post_ids := post_ids || pid;

    n_total := n_total + jsonb_array_length(g.rows);
    with src as (
      select distinct on (r->>'id') r from jsonb_array_elements(g.rows) r order by r->>'id'
    ), ins as (
      insert into comments(id, post_id, parent_id, text, ts, like_count, reply_count, url, user_id,
                           user_name, user_homepage, auto_label, auto_category, auto_urgency, auto_location,
                           matched, is_problem, category, urgency, location, status)
      select r->>'id', pid, nullif(r->>'parent_id', ''), r->>'text', nullif(r->>'ts', '')::timestamp,
             coalesce((r->>'like_count')::int, 0), coalesce((r->>'reply_count')::int, 0), r->>'url',
             r->>'user_id', r->>'user_name', r->>'user_homepage',
             r->>'auto_label', r->>'category', r->>'urgency', r->>'location', r->>'matched',
             coalesce((r->>'is_problem')::boolean, false), nullif(r->>'category', ''),
             nullif(r->>'urgency', ''), r->>'location',
             case when coalesce((r->>'is_problem')::boolean, false) then 'ใหม่' end
      from src
      on conflict (id) do nothing
      returning 1
    )
    select count(*) into n from ins;
    n_added := n_added + n;
    n_dup := n_dup + jsonb_array_length(g.rows) - n;

    -- คอมเมนต์เดิม: อัปเดตยอดไลก์/ตอบกลับ
    update comments c set like_count = coalesce((r->>'like_count')::int, 0),
                          reply_count = coalesce((r->>'reply_count')::int, 0)
      from jsonb_array_elements(g.rows) r
     where c.id = r->>'id' and c.imported_at < now();

    update posts set last_imported = now(), first_imported = coalesce(first_imported, now()) where id = pid;
  end loop;

  insert into imports(id, filename, post_id, total, added, duplicate, user_id, user_email)
  values (coalesce(nullif(p_batch, ''), gen_random_uuid()::text), left(p_filename, 200),
          array_to_string(array(select distinct unnest(post_ids)), ','), n_total, n_added, n_dup, auth.uid(), who_email)
  on conflict (id) do update set total = imports.total + excluded.total, added = imports.added + excluded.added,
    duplicate = imports.duplicate + excluded.duplicate, at = now();

  return jsonb_build_object('total', n_total, 'added', n_added, 'duplicate', n_dup,
    'posts', to_jsonb(array(select distinct unnest(post_ids))),
    'warnings', to_jsonb(array(select distinct unnest(warns))));
end $$;

-- คัดกรองใหม่หลังแก้ keyword (เฉพาะเรื่องที่ยังไม่ตรวจทาน) — หน้าเว็บคัดกรองแล้วส่งผลมา
create or replace function public.apply_classification(p_rows jsonb) returns int
language plpgsql security definer set search_path = public as $$
declare n int;
begin
  if not public.is_admin() then raise exception 'เฉพาะผู้ดูแล'; end if;
  perform set_config('app.skip_history', '1', true);
  update comments c set
    auto_label = r->>'auto_label', auto_category = r->>'category', auto_urgency = r->>'urgency',
    auto_location = r->>'location', matched = r->>'matched',
    is_problem = (r->>'is_problem')::boolean, category = nullif(r->>'category', ''),
    urgency = nullif(r->>'urgency', ''), location = r->>'location',
    status = case when (r->>'is_problem')::boolean then coalesce(c.status, 'ใหม่') else c.status end
  from jsonb_array_elements(p_rows) r
  where c.id = r->>'id' and c.review = 'pending';
  get diagnostics n = row_count;
  return n;
end $$;

-- PDPA: ลบชื่อ/ลิงก์ผู้แจ้ง (p_before = null → ทั้งหมด)
create or replace function public.purge_personal(p_before date) returns int
language plpgsql security definer set search_path = public as $$
declare n int;
begin
  if not public.is_admin() then raise exception 'เฉพาะผู้ดูแล'; end if;
  perform set_config('app.skip_history', '1', true);
  update comments set user_name = '(ลบแล้ว)', user_id = '', user_homepage = '', url = ''
   where p_before is null or ts < p_before;
  get diagnostics n = row_count;
  return n;
end $$;

-- ---------------------------------------------------------------------------
-- ค้นหา / สรุป (ทำงานตามสิทธิ์ของผู้เรียก — RLS มีผล)
-- f = {"post","from","to","category","urgency","status","cats":[...],"q","open"}
-- ---------------------------------------------------------------------------
create or replace function public.comment_where(f jsonb, p_view text) returns text
language plpgsql immutable as $$
declare
  w text[];
  v text := coalesce(p_view, 'problems');
begin
  w := array[case v
    when 'problems'   then 'is_problem and review <> ''rejected'''
    when 'review'     then 'is_problem and review = ''pending'''
    when 'unmatched'  then 'not is_problem and review = ''pending'' and auto_label in (''unmatched'',''not_problem'')'
    when 'needs_view' then 'auto_label = ''needs_view'' and review = ''pending'''
    when 'rejected'   then '(review = ''rejected'' or (not is_problem and review = ''confirmed''))'
    else 'true' end];
  if coalesce(f->>'post', '') <> '' then w := w || format('post_id = %L', f->>'post'); end if;
  if coalesce(f->>'from', '') <> '' then w := w || format('ts >= %L::date', f->>'from'); end if;
  if coalesce(f->>'to', '') <> '' then w := w || format('ts < %L::date + 1', f->>'to'); end if;
  if coalesce(f->>'category', '') <> '' then w := w || format('category = %L', f->>'category'); end if;
  if coalesce(f->>'urgency', '') <> '' then w := w || format('urgency = %L', f->>'urgency'); end if;
  if coalesce(f->>'status', '') <> '' then w := w || format('status = %L', f->>'status'); end if;
  if jsonb_typeof(f->'cats') = 'array' then
    w := w || format('category = any(%L::text[])', array(select jsonb_array_elements_text(f->'cats')));
  end if;
  if coalesce(f->>'open', '') not in ('', '0', 'false') then w := w || 'coalesce(status, '''') <> ''เสร็จสิ้น'''::text; end if;
  if coalesce(f->>'q', '') <> '' then
    w := w || format('(text ilike %1$L or location ilike %1$L or user_name ilike %1$L or note ilike %1$L)',
                     '%' || replace(replace(replace(f->>'q', '\', '\\'), '%', '\%'), '_', '\_') || '%');
  end if;
  return array_to_string(w, ' and ');
end $$;

create or replace function public.list_comments(f jsonb, p_view text, p_limit int, p_offset int)
returns jsonb language plpgsql stable set search_path = public as $$
declare
  w text := public.comment_where(f, p_view);
  total int;
  rows jsonb;
begin
  execute 'select count(*) from comments where ' || w into total;
  execute format($q$
    select coalesce(jsonb_agg(x), '[]') from (
      select c.*, p.title as post_title from comments c left join posts p on p.id = c.post_id
      where %s
      order by %s
      limit %s offset %s) x$q$,
    replace(w, 'note ilike', 'c.note ilike'),
    case when p_view = 'problems'
         then 'case urgency when ''urgent'' then 0 when ''normal'' then 1 else 2 end, ts desc'
         else 'ts desc' end,
    least(greatest(coalesce(p_limit, 100), 1), 100000), greatest(coalesce(p_offset, 0), 0))
  into rows;
  return jsonb_build_object('total', total, 'rows', rows);
end $$;

create or replace function public.dashboard_stats(f jsonb) returns jsonb
language plpgsql stable set search_path = public as $$
declare
  w text := public.comment_where(f, 'problems');
  w_all text := public.comment_where(
    jsonb_build_object('post', f->'post', 'from', f->'from', 'to', f->'to'), 'all');
  res jsonb;
  part jsonb;
begin
  execute format($q$select jsonb_build_object(
      'total', count(*),
      'urgent_open', count(*) filter (where urgency = 'urgent' and coalesce(status, '') <> 'เสร็จสิ้น'),
      'in_progress', count(*) filter (where status in ('รับเรื่อง', 'กำลังดำเนินการ', 'ส่งต่อหน่วยงาน')),
      'done', count(*) filter (where status = 'เสร็จสิ้น'),
      'new', count(*) filter (where status = 'ใหม่')) from comments where %s$q$, w) into res;
  execute format($q$select jsonb_build_object('all_comments', count(*),
      'pending_review', count(*) filter (where review = 'pending' and (is_problem or auto_label = 'needs_view')))
      from comments where %s$q$, w_all) into part;
  res := jsonb_build_object('summary', res || part);
  execute format('select coalesce(jsonb_object_agg(coalesce(category, ''''), n), ''{}'') from (select category, count(*) n from comments where %s group by 1) x', w) into part;
  res := res || jsonb_build_object('by_category', part);
  execute format('select coalesce(jsonb_object_agg(coalesce(urgency, ''''), n), ''{}'') from (select urgency, count(*) n from comments where %s group by 1) x', w) into part;
  res := res || jsonb_build_object('by_urgency', part);
  execute format('select coalesce(jsonb_object_agg(coalesce(status, ''''), n), ''{}'') from (select status, count(*) n from comments where %s group by 1) x', w) into part;
  res := res || jsonb_build_object('by_status', part);
  execute format($q$select coalesce(jsonb_agg(jsonb_build_array(k, n) order by k), '[]') from (
      select to_char(date_trunc('hour', ts), 'YYYY-MM-DD HH24') k, count(*) n
      from comments where %s and ts is not null group by 1) x$q$, w) into part;
  res := res || jsonb_build_object('hours', part);
  execute format($q$select coalesce(jsonb_agg(x), '[]') from (
      select location, count(*) n, count(distinct user_id) people,
             count(*) filter (where urgency = 'urgent') urgent, max(ts) last
      from comments where %s and coalesce(location, '') <> ''
      group by location order by n desc, last desc limit 15) x$q$, w) into part;
  res := res || jsonb_build_object('hotspots', part);
  execute format($q$select coalesce(jsonb_agg(x), '[]') from (
      select id, text, ts, location, category, status, user_name, url from comments
      where %s and urgency = 'urgent' and status in ('ใหม่', 'รับเรื่อง') order by ts limit 30) x$q$, w) into part;
  return res || jsonb_build_object('urgent_open', part);
end $$;

create or replace function public.posts_overview() returns jsonb
language sql stable set search_path = public as $$
  select coalesce(jsonb_agg(x order by x.active desc, coalesce(x.last_imported, x.created_at) desc), '[]') from (
    select p.*, count(c.id) n,
      count(*) filter (where c.is_problem and c.review <> 'rejected') problems,
      count(*) filter (where c.is_problem and c.review <> 'rejected' and c.urgency = 'urgent'
                         and coalesce(c.status, '') <> 'เสร็จสิ้น') urgent_open,
      count(*) filter (where c.review = 'pending' and (c.is_problem or c.auto_label = 'needs_view')) pending,
      max(c.ts) last_comment
    from posts p left join comments c on c.post_id = p.id
    group by p.id) x
$$;

-- ฟังก์ชันเรียกได้เฉพาะคนที่ล็อกอิน (และภายในฟังก์ชันตรวจสิทธิ์ซ้ำ / RLS มีผล)
revoke execute on all functions in schema public from public, anon;
grant execute on function public.app_role(), public.is_admin(), public.is_member(),
  public.set_user_role(uuid, text), public.import_comments(jsonb, text, text, text),
  public.apply_classification(jsonb), public.purge_personal(date),
  public.comment_where(jsonb, text), public.list_comments(jsonb, text, int, int),
  public.dashboard_stats(jsonb), public.posts_overview() to authenticated;
